import jsPDF from 'jspdf';
import 'jspdf-autotable';

export function exportPortfolioPDF(portfolio) {
  const doc = new jsPDF();
  const holdings = portfolio?.holdings || [];

  // Title
  doc.setFontSize(20);
  doc.setTextColor(0, 212, 170);
  doc.text('AI Stock Advisor — Portfolio Report', 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 28);

  // Summary
  const totalValue = holdings.reduce((s, h) => s + (h.market_value || 0), 0);
  const totalCost = holdings.reduce((s, h) => s + h.shares * h.buy_price, 0);
  const totalPnL = totalValue - totalCost;

  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  doc.setFillColor(20, 26, 46);
  doc.roundedRect(14, 34, 180, 18, 3, 3, 'F');
  doc.setTextColor(200, 200, 200);
  doc.text(`Total Value: $${totalValue.toLocaleString('en-US', { maximumFractionDigits: 2 })}`, 20, 44);
  doc.text(`Total P&L: ${totalPnL >= 0 ? '+' : ''}$${totalPnL.toLocaleString('en-US', { maximumFractionDigits: 2 })}`, 100, 44);

  // Holdings table
  const tableData = holdings.map((h) => {
    const pnl = (h.market_value || 0) - h.shares * h.buy_price;
    const pnlPct = h.buy_price > 0 ? ((h.current_price - h.buy_price) / h.buy_price * 100) : 0;
    return [
      h.symbol,
      h.shares.toString(),
      `$${h.buy_price?.toFixed(2)}`,
      `$${h.current_price?.toFixed(2) || '—'}`,
      `$${(h.market_value || 0).toLocaleString('en-US', { maximumFractionDigits: 2 })}`,
      `${pnl >= 0 ? '+' : ''}${pnlPct.toFixed(2)}%`,
    ];
  });

  doc.autoTable({
    startY: 58,
    head: [['Symbol', 'Shares', 'Buy Price', 'Current', 'Value', 'P&L %']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [0, 212, 170], textColor: [0, 0, 0], fontStyle: 'bold' },
    bodyStyles: { textColor: [200, 200, 200] },
    alternateRowStyles: { fillColor: [20, 26, 46] },
    styles: { fillColor: [15, 20, 34], fontSize: 9 },
  });

  // Footer
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('This is not financial advice. Generated by AI Stock Advisor.', 14, finalY);

  doc.save('portfolio-report.pdf');
}

export function exportStockReportPDF(report) {
  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.setTextColor(0, 212, 170);
  doc.text(`AI Stock Advisor — ${report.symbol || 'Stock'} Report`, 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 28);

  // Content
  doc.setFontSize(11);
  doc.setTextColor(200, 200, 200);
  const lines = doc.splitTextToSize(report.report || report.content || 'No data', 180);
  doc.text(lines, 14, 38);

  doc.save(`${(report.symbol || 'stock').toLowerCase()}-report.pdf`);
}
