export async function exportPortfolioPDF(portfolio) {
  try {
    if (typeof window === 'undefined') throw new Error('PDF export only works in browser');

    // Dynamically import jspdf and autotable to avoid SSR/build issues
    const jspdfModule = await import('jspdf');
    await import('jspdf-autotable');
    const { jsPDF } = jspdfModule;
    if (typeof jsPDF !== 'function') throw new Error('jsPDF import failed');

    const doc = new jsPDF();
    const holdings = portfolio?.holdings || [];

    // Title
    doc.setFontSize(20);
    doc.setTextColor(0, 212, 170);
    doc.text('InvestIQ — Portfolio Report', 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 28);

    // Summary
    const totalValue = holdings.reduce((s, h) => s + (h.market_value || 0), 0);
    const totalCost = holdings.reduce((s, h) => s + h.shares * h.buy_price, 0);
    const totalPnL = totalValue - totalCost;

    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.setFillColor(20, 26, 46);
    doc.roundedRect(14, 34, 180, 18, 3, 3, 'F');
    doc.setTextColor(200, 200, 200);
    doc.text(`Total Value: $${totalValue.toLocaleString('en-US', { maximumFractionDigits: 2 })}`, 20, 44);
    doc.text(`Total P&L: ${totalPnL >= 0 ? '+' : ''}$${totalPnL.toLocaleString('en-US', { maximumFractionDigits: 2 })}`, 100, 44);

    // Holdings table
    const tableData = holdings.map((h) => {
      const pnl = (h.market_value || 0) - h.shares * h.buy_price;
      const pnlPct = h.buy_price > 0 ? ((h.current_price - h.buy_price) / h.buy_price * 100) : 0;
      return [
        h.symbol,
        h.shares.toString(),
        `$${h.buy_price?.toFixed(2)}`,
        `$${h.current_price?.toFixed(2) || '—'}`,
        `$${(h.market_value || 0).toLocaleString('en-US', { maximumFractionDigits: 2 })}`,
        `${pnl >= 0 ? '+' : ''}${pnlPct.toFixed(2)}%`,
      ];
    });

    doc.autoTable({
      startY: 58,
      head: [['Symbol', 'Shares', 'Buy Price', 'Current', 'Value', 'P&L %']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [0, 212, 170], textColor: [0, 0, 0], fontStyle: 'bold' },
      bodyStyles: { textColor: [200, 200, 200] },
      alternateRowStyles: { fillColor: [20, 26, 46] },
      styles: { fillColor: [15, 20, 34], fontSize: 9 },
    });

    // Footer
    const finalY = doc.lastAutoTable?.finalY ? doc.lastAutoTable.finalY + 10 : 200;
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('This is not financial advice. Generated by InvestIQ.', 14, finalY);

    doc.save('portfolio-report.pdf');
  } catch (err) {
    console.error('PDF export error:', err);
    let errorMsg = 'Failed to generate PDF.';
    if (err && err.message) errorMsg += '\n' + err.message;
    alert(errorMsg + '\nDownloading CSV instead.');

    // Fallback: CSV export
    const holdings = portfolio?.holdings || [];
    if (holdings && holdings.length > 0) {
      const csvRows = [
        ['Symbol', 'Shares', 'Buy Price', 'Current', 'Value', 'P&L %'],
        ...holdings.map(h => [
          h.symbol,
          h.shares,
          h.buy_price,
          h.current_price || '',
          h.market_value || '',
          h.buy_price > 0 ? (((h.current_price - h.buy_price) / h.buy_price) * 100).toFixed(2) + '%' : ''
        ])
      ];
      const csvContent = csvRows.map(row => row.join(',')).join('\n');
      const blob = new Blob([csvContent], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'portfolio-report.csv';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  }
}

export async function exportStockReportPDF(report) {
  try {
    if (typeof window === 'undefined') throw new Error('PDF export only works in browser');
    const jspdfModule = await import('jspdf');
    await import('jspdf-autotable');
    const { jsPDF } = jspdfModule;
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.setTextColor(0, 212, 170);
    doc.text(`InvestIQ — ${report.symbol || 'Stock'} Report`, 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 28);

    // Content
    doc.setFontSize(11);
    doc.setTextColor(200, 200, 200);
    const lines = doc.splitTextToSize(report.report || report.content || 'No data', 180);
    doc.text(lines, 14, 38);

    doc.save(`${(report.symbol || 'stock').toLowerCase()}-report.pdf`);
  } catch (err) {
    console.error('Stock PDF export error:', err);
    alert('Failed to generate stock PDF. ' + (err?.message || ''));
  }
}
